[2024-04-24T18:25:01.963+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: daily_task_dag.webscrapping manual__2024-04-24T18:24:56.047731+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
