[2024-04-23T15:09:38.861+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T15:09:38.883+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.task_2 manual__2024-04-23T15:09:35.162801+00:00 [queued]>
[2024-04-23T15:09:38.890+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.task_2 manual__2024-04-23T15:09:35.162801+00:00 [queued]>
[2024-04-23T15:09:38.890+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T15:09:38.902+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): task_2> on 2024-04-23 15:09:35.162801+00:00
[2024-04-23T15:09:38.912+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'task_2', 'manual__2024-04-23T15:09:35.162801+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmp57lb5pze']
[2024-04-23T15:09:38.914+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask task_2
[2024-04-23T15:09:38.915+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=803) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T15:09:38.916+0000] {standard_task_runner.py:63} INFO - Started process 816 to run task
[2024-04-23T15:09:38.953+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.task_2 manual__2024-04-23T15:09:35.162801+00:00 [running]> on host 21330f56d46c
[2024-04-23T15:09:39.351+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T15:09:35.162801+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T15:09:35.162801+00:00'
[2024-04-23T15:09:39.352+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T15:09:39.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T15:09:39.377+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DataMLOps.py", line 31, in print_hello
    loaded_model = pickle.load(file)
                   ^^^^^^^^^^^^^^^^^
  File "sklearn/tree/_tree.pyx", line 865, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1571, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
[2024-04-23T15:09:39.389+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_task_dag, task_id=task_2, execution_date=20240423T150935, start_date=20240423T150938, end_date=20240423T150939
[2024-04-23T15:09:39.399+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task task_2 (node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]; 816)
[2024-04-23T15:09:39.411+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T15:09:39.432+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T15:09:39.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
