[2024-04-23T18:14:51.043+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T18:14:51.065+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.predict_data manual__2024-04-23T18:14:12.531720+00:00 [queued]>
[2024-04-23T18:14:51.071+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.predict_data manual__2024-04-23T18:14:12.531720+00:00 [queued]>
[2024-04-23T18:14:51.071+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T18:14:51.083+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): predict_data> on 2024-04-23 18:14:12.531720+00:00
[2024-04-23T18:14:51.092+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'predict_data', 'manual__2024-04-23T18:14:12.531720+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmpjll67ek6']
[2024-04-23T18:14:51.094+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask predict_data
[2024-04-23T18:14:51.095+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=783) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T18:14:51.095+0000] {standard_task_runner.py:63} INFO - Started process 798 to run task
[2024-04-23T18:14:51.123+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.predict_data manual__2024-04-23T18:14:12.531720+00:00 [running]> on host 24f05fbfe784
[2024-04-23T18:14:51.180+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='predict_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T18:14:12.531720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T18:14:12.531720+00:00'
[2024-04-23T18:14:51.181+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T18:14:51.207+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T18:14:51.207+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DataMLOps.py", line 547, in predict_data
    loaded_model = pickle.load(pickle_in)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
[2024-04-23T18:14:51.216+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_task_dag, task_id=predict_data, execution_date=20240423T181412, start_date=20240423T181451, end_date=20240423T181451
[2024-04-23T18:14:51.225+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task predict_data (code() argument 13 must be str, not int; 798)
[2024-04-23T18:14:51.269+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T18:14:51.283+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T18:14:51.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
