[2024-04-23T16:50:52.648+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T16:50:52.670+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-23T16:45:00.446812+00:00 [queued]>
[2024-04-23T16:50:52.675+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-23T16:45:00.446812+00:00 [queued]>
[2024-04-23T16:50:52.676+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-23T16:50:52.687+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_warehouse> on 2024-04-23 16:45:00.446812+00:00
[2024-04-23T16:50:52.695+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'load_warehouse', 'manual__2024-04-23T16:45:00.446812+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmpnw3nahk6']
[2024-04-23T16:50:52.697+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_warehouse
[2024-04-23T16:50:52.698+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=700) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T16:50:52.698+0000] {standard_task_runner.py:63} INFO - Started process 713 to run task
[2024-04-23T16:50:52.727+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.load_warehouse manual__2024-04-23T16:45:00.446812+00:00 [running]> on host 5ee87de5b592
[2024-04-23T16:50:52.783+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='load_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T16:45:00.446812+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T16:45:00.446812+00:00'
[2024-04-23T16:50:52.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T16:50:52.951+0000] {logging_mixin.py:188} INFO - Database 'bt4301_gp_datawarehouse' already exists. No need to create it.
[2024-04-23T16:50:52.958+0000] {logging_mixin.py:188} INFO - MySQL connection is closed
[2024-04-23T16:50:53.628+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/DataMLOps.py:298 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-23T16:50:53.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T16:50:53.630+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DataMLOps.py", line 302, in load_warehouse
    STOPWORDS = stopwords.words('english')
                ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

[2024-04-23T16:50:53.641+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=daily_task_dag, task_id=load_warehouse, execution_date=20240423T164500, start_date=20240423T165052, end_date=20240423T165053
[2024-04-23T16:50:53.652+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task load_warehouse (
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
; 713)
[2024-04-23T16:50:53.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T16:50:53.689+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T16:50:53.695+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
