[2024-04-24T17:47:14.017+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T17:47:14.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.upload_finetined_model manual__2024-04-24T17:46:12.151954+00:00 [queued]>
[2024-04-24T17:47:14.044+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.upload_finetined_model manual__2024-04-24T17:46:12.151954+00:00 [queued]>
[2024-04-24T17:47:14.045+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-24T17:47:14.058+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_finetined_model> on 2024-04-24 17:46:12.151954+00:00
[2024-04-24T17:47:14.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'upload_finetined_model', 'manual__2024-04-24T17:46:12.151954+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmpr0eitu6e']
[2024-04-24T17:47:14.069+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask upload_finetined_model
[2024-04-24T17:47:14.070+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=448) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T17:47:14.071+0000] {standard_task_runner.py:63} INFO - Started process 461 to run task
[2024-04-24T17:47:14.104+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.upload_finetined_model manual__2024-04-24T17:46:12.151954+00:00 [running]> on host 8a1adea61cd5
[2024-04-24T17:47:14.167+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='upload_finetined_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T17:46:12.151954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T17:46:12.151954+00:00'
[2024-04-24T17:47:14.168+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T17:47:14.181+0000] {logging_mixin.py:188} INFO - loading data
[2024-04-24T17:47:14.193+0000] {logging_mixin.py:188} INFO - loading model
[2024-04-24T17:47:16.791+0000] {logging_mixin.py:188} INFO - preparing data
[2024-04-24T17:47:16.792+0000] {logging_mixin.py:188} INFO - PREDICTING data
[2024-04-24T17:48:04.917+0000] {logging_mixin.py:188} INFO - ROC AUC Score: 0.957703265395573
[2024-04-24T17:48:04.918+0000] {logging_mixin.py:188} INFO - 0.8689320388349514
[2024-04-24T17:48:04.918+0000] {logging_mixin.py:188} INFO - uploading model
[2024-04-24T17:48:04.960+0000] {logging_mixin.py:188} WARNING - 2024/04/24 17:48:04 INFO mlflow.tracking.fluent: Experiment with name 'MLflow - Finetune Model' does not exist. Creating a new experiment.
[2024-04-24T17:48:05.018+0000] {logging_mixin.py:188} WARNING - 2024/04/24 17:48:05 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-04-24T17:48:05.963+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/types/utils.py:394 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2024-04-24T17:48:08.584+0000] {logging_mixin.py:188} WARNING - Successfully registered model 'mlops_finetune_model'.
[2024-04-24T17:48:08.608+0000] {logging_mixin.py:188} WARNING - 2024/04/24 17:48:08 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: mlops_finetune_model, version 1
[2024-04-24T17:48:08.608+0000] {logging_mixin.py:188} WARNING - Created version '1' of model 'mlops_finetune_model'.
[2024-04-24T17:48:08.626+0000] {logging_mixin.py:188} INFO - runs:/d32e7b686fc0468485e99e3e2f4b06c5/mlops_finetune_model
[2024-04-24T17:48:08.644+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-24T17:48:08.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T17:48:08.651+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=daily_task_dag, task_id=upload_finetined_model, execution_date=20240424T174612, start_date=20240424T174714, end_date=20240424T174808
[2024-04-24T17:48:08.702+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-24T17:48:08.713+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T17:48:08.716+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
