[2024-04-23T16:41:50.391+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T16:41:50.414+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.webscrapping manual__2024-04-23T16:41:46.253747+00:00 [queued]>
[2024-04-23T16:41:50.423+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.webscrapping manual__2024-04-23T16:41:46.253747+00:00 [queued]>
[2024-04-23T16:41:50.424+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T16:41:50.439+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): webscrapping> on 2024-04-23 16:41:46.253747+00:00
[2024-04-23T16:41:50.458+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'webscrapping', 'manual__2024-04-23T16:41:46.253747+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmpg89gcqbw']
[2024-04-23T16:41:50.460+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask webscrapping
[2024-04-23T16:41:50.461+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=215) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T16:41:50.461+0000] {standard_task_runner.py:63} INFO - Started process 243 to run task
[2024-04-23T16:41:50.508+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.webscrapping manual__2024-04-23T16:41:46.253747+00:00 [running]> on host 5ee87de5b592
[2024-04-23T16:41:50.594+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='webscrapping' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T16:41:46.253747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T16:41:46.253747+00:00'
[2024-04-23T16:41:50.595+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T16:42:21.314+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T16:42:21.315+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DataMLOps.py", line 188, in webscrapping
    client = storage.Client.from_service_account_json(json_credentials_path=path_to_private_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ethereal-anthem-417503-1d749c7332fa.json'
[2024-04-23T16:42:21.337+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_task_dag, task_id=webscrapping, execution_date=20240423T164146, start_date=20240423T164150, end_date=20240423T164221
[2024-04-23T16:42:21.353+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task webscrapping ([Errno 2] No such file or directory: 'ethereal-anthem-417503-1d749c7332fa.json'; 243)
[2024-04-23T16:42:21.398+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T16:42:21.414+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T16:42:21.418+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
